# Generated by Django 3.0.6 on 2020-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udnParticipants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Enter your full name', max_length=100)),
                ('age', models.IntegerField(help_text='Enter your age')),
                ('siblings', models.BooleanField(help_text='Click on the checkbox if you have siblings')),
                ('environmentExposures', models.TextField()),
                ('geneticMutations', models.TextField()),
                ('reviewItem', models.CharField(choices=[('Not Reviewed', ''), ('Reviewed - Accepted', ''), ('Not Accepted', '')], default='Not Reviewed', editable=False, max_length=20)),
            ],
        ),
    ]
