# Generated by Django 3.0.6 on 2020-05-27 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('udnParticipants', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
