# Generated by Django 3.0.6 on 2020-05-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udnParticipants', '0007_auto_20200527_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reviewItem',
            field=models.CharField(choices=[('NR', 'Not Reviewed'), ('RA', 'Reviewed Accepted'), ('NA', 'Not Accepted')], default='Not Reviewed', max_length=20),
        ),
    ]
