# Generated by Django 3.0.6 on 2020-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udnParticipants', '0008_auto_20200527_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reviewItem',
            field=models.CharField(choices=[('NR', 'Not Reviewed'), ('RA', 'Reviewed - Accepted'), ('RNA', 'Reviewed - Not Accepted')], default='Not Reviewed', max_length=20),
        ),
    ]
